### PR TITLE
Prepare for 0.3.7 release

### PR DESCRIPTION
**Pull request by briansmith**
Contributed on behalf of Buoyant, Inc.

Signed-off-by: Brian Smith <brian@briansmith.org>

### CODE REVIEW

**Comment by briansmith** [comment]
It would be useful to have 0.3.7 released with the updated `remove_dir_all` dependency because, among other things, the newer version of `remove_dir_all` makes its dependencies on winapi windows-target-specific. That means that winapi won't be downloaded when building for non-Windows targets with the new version, like it was with the old version.

**Comment by KodrAus** [comment]
Thanks @briansmith! I'll get this published.

**Comment by KodrAus** [comment]
[All done](https://crates.io/crates/tempdir/0.3.7)

**Comment by briansmith** [comment]
> All done

Awesome! Thanks for the quick turnaround.

**Pull request merged**
