### PR TITLE
Added Windows remove_dir_all implementation from #31944

### LINKED ISSUE #15: TempDir affected by remove_dir_all unreliability on windows
I have test cases where TempDir fails to remove the directory mysteriously and irregularly.

cc https://github.com/rust-lang/rust/issues/29497

### PR DESCRIPTION
**Pull request by XAMPPRocky**
fixes #15

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Perhaps this could use winapi instead of vendoring large parts of the standard library? (may also help readability as well)

**Comment by retep998** [comment]
Practically all of that windows api stuff should be available in `winapi`.

**Comment by brson** [comment]
Neat! I agree that it would be better to use winapi here, and I'd also prefer if you would publish `remove_dir_all` as a crate so others can use it as well.

**Comment by brson** [comment]
Next thing to do here is extract the function to its own crate, convert it to use winapi and then use that crate in tempdir.

**Comment by XAMPPRocky** [comment]
I have pulled it out into a new crate, [`remove_dir_all`](https://github.com/Aaronepower/remove_dir_all/) which now uses `winapi`.

**Comment by pwoolcoc** [comment]
@Aaronepower I opened a pr on `remove_dir_all` that should fix the build issue

**Comment by brson** [comment]
@Aaronepower thank you! Looks like there's a bit more to do here before merging, but thanks for picking it up again.

**Comment by XAMPPRocky** [comment]
@brson I've updated it with @pwoolcoc 's changes. Seems like it works fine now!

**Comment by brson** [comment]
Thanks @Aaronepower!

**Pull request merged**
